version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=codemaker
      - POSTGRES_PASSWORD=TH3c0d3M4k3R!
      - POSTGRES_DB=mastermind

  web:
    build: .
    env_file: ./.env
    command: "/code/docker-entrypoint.sh"
    volumes:
      - ./mastermind:/code
    ports:
      - "8000:8000"
    depends_on:
      - db